### ISSUE TITLE
select zero

### ISSUE THREAD

**Issue by flucky88** [cameronpoe/blacktoolin#1]
error: target not found: openvas-cli
error: target not found: openvas-manager
error: target not found: openvas-scanner
warning: ntop-5.0.1-12 is up to date -- reinstalling
warning: aircrack-ng-1.5.2-1 is up to date -- reinstalling
warning: mdk3-v6-7 is up to date -- reinstalling
error: target not found: dradis
error: target not found: keepnote
warning: arduino-1:1.8.9-3 is up to date -- reinstalling

im use manjaro kde .thanks

**Comment by preemware** [comment]
Fixed in latest commit.
